// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvserver.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrGetTableRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrGetTableRequest) Reset()         { *m = CreateOrGetTableRequest{} }
func (m *CreateOrGetTableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrGetTableRequest) ProtoMessage()    {}
func (*CreateOrGetTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{0}
}

func (m *CreateOrGetTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrGetTableRequest.Unmarshal(m, b)
}
func (m *CreateOrGetTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrGetTableRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrGetTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrGetTableRequest.Merge(m, src)
}
func (m *CreateOrGetTableRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrGetTableRequest.Size(m)
}
func (m *CreateOrGetTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrGetTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrGetTableRequest proto.InternalMessageInfo

func (m *CreateOrGetTableRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteTableRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTableRequest) Reset()         { *m = DeleteTableRequest{} }
func (m *DeleteTableRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTableRequest) ProtoMessage()    {}
func (*DeleteTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{1}
}

func (m *DeleteTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTableRequest.Unmarshal(m, b)
}
func (m *DeleteTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTableRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTableRequest.Merge(m, src)
}
func (m *DeleteTableRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTableRequest.Size(m)
}
func (m *DeleteTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTableRequest proto.InternalMessageInfo

func (m *DeleteTableRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BeginTransactionRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginTransactionRequest) Reset()         { *m = BeginTransactionRequest{} }
func (m *BeginTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*BeginTransactionRequest) ProtoMessage()    {}
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{2}
}

func (m *BeginTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginTransactionRequest.Unmarshal(m, b)
}
func (m *BeginTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginTransactionRequest.Marshal(b, m, deterministic)
}
func (m *BeginTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginTransactionRequest.Merge(m, src)
}
func (m *BeginTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_BeginTransactionRequest.Size(m)
}
func (m *BeginTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginTransactionRequest proto.InternalMessageInfo

func (m *BeginTransactionRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type BeginTransactionReply struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginTransactionReply) Reset()         { *m = BeginTransactionReply{} }
func (m *BeginTransactionReply) String() string { return proto.CompactTextString(m) }
func (*BeginTransactionReply) ProtoMessage()    {}
func (*BeginTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{3}
}

func (m *BeginTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginTransactionReply.Unmarshal(m, b)
}
func (m *BeginTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginTransactionReply.Marshal(b, m, deterministic)
}
func (m *BeginTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginTransactionReply.Merge(m, src)
}
func (m *BeginTransactionReply) XXX_Size() int {
	return xxx_messageInfo_BeginTransactionReply.Size(m)
}
func (m *BeginTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_BeginTransactionReply proto.InternalMessageInfo

func (m *BeginTransactionReply) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type CommitTransactionRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTransactionRequest) Reset()         { *m = CommitTransactionRequest{} }
func (m *CommitTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CommitTransactionRequest) ProtoMessage()    {}
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{4}
}

func (m *CommitTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTransactionRequest.Unmarshal(m, b)
}
func (m *CommitTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTransactionRequest.Marshal(b, m, deterministic)
}
func (m *CommitTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTransactionRequest.Merge(m, src)
}
func (m *CommitTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CommitTransactionRequest.Size(m)
}
func (m *CommitTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTransactionRequest proto.InternalMessageInfo

func (m *CommitTransactionRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type RollbackTransactionRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackTransactionRequest) Reset()         { *m = RollbackTransactionRequest{} }
func (m *RollbackTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackTransactionRequest) ProtoMessage()    {}
func (*RollbackTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{5}
}

func (m *RollbackTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackTransactionRequest.Unmarshal(m, b)
}
func (m *RollbackTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackTransactionRequest.Marshal(b, m, deterministic)
}
func (m *RollbackTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackTransactionRequest.Merge(m, src)
}
func (m *RollbackTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackTransactionRequest.Size(m)
}
func (m *RollbackTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackTransactionRequest proto.InternalMessageInfo

func (m *RollbackTransactionRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type AddRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{6}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

func (m *AddRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AddRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DeleteRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UpdateRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{8}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

func (m *UpdateRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{9}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{10}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ListRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{11}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type ListResponse struct {
	Values               map[string][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b14dcbe5169b67b, []int{12}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetValues() map[string][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateOrGetTableRequest)(nil), "pb.CreateOrGetTableRequest")
	proto.RegisterType((*DeleteTableRequest)(nil), "pb.DeleteTableRequest")
	proto.RegisterType((*BeginTransactionRequest)(nil), "pb.BeginTransactionRequest")
	proto.RegisterType((*BeginTransactionReply)(nil), "pb.BeginTransactionReply")
	proto.RegisterType((*CommitTransactionRequest)(nil), "pb.CommitTransactionRequest")
	proto.RegisterType((*RollbackTransactionRequest)(nil), "pb.RollbackTransactionRequest")
	proto.RegisterType((*AddRequest)(nil), "pb.AddRequest")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*UpdateRequest)(nil), "pb.UpdateRequest")
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
	proto.RegisterType((*ListRequest)(nil), "pb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "pb.ListResponse")
	proto.RegisterMapType((map[string][]byte)(nil), "pb.ListResponse.ValuesEntry")
}

func init() { proto.RegisterFile("kvserver.proto", fileDescriptor_1b14dcbe5169b67b) }

var fileDescriptor_1b14dcbe5169b67b = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0x9b, 0xa6, 0xab, 0xb4, 0x9b, 0xfd, 0xe9, 0x3c, 0xd8, 0x42, 0x06, 0xa8, 0x32, 0x2f,
	0x91, 0x80, 0x54, 0x6c, 0x80, 0x06, 0x2f, 0x68, 0x8c, 0xa9, 0xaa, 0x56, 0x31, 0x29, 0x8c, 0xbd,
	0x4e, 0xc9, 0x72, 0xa9, 0xa2, 0xa6, 0x49, 0x48, 0xdc, 0x6a, 0x79, 0xe2, 0x43, 0xf3, 0x05, 0x90,
	0xed, 0x95, 0x84, 0x36, 0x09, 0xed, 0x5b, 0x72, 0x7d, 0xce, 0xf1, 0xb5, 0x7d, 0x7f, 0xb0, 0x33,
	0x9e, 0xa5, 0x98, 0xcc, 0x30, 0xb1, 0xe2, 0x24, 0x62, 0x11, 0x69, 0xc6, 0xae, 0x71, 0x34, 0x8a,
	0xa2, 0x51, 0x80, 0x3d, 0x51, 0x71, 0xa7, 0x3f, 0x7a, 0x38, 0x89, 0x59, 0x26, 0x05, 0xf4, 0x35,
	0x1c, 0x9e, 0x27, 0xe8, 0x30, 0xbc, 0x4a, 0xfa, 0xc8, 0xae, 0x1d, 0x37, 0x40, 0x1b, 0x7f, 0x4e,
	0x31, 0x65, 0x84, 0x40, 0x2b, 0x74, 0x26, 0xa8, 0x2b, 0x5d, 0xc5, 0xdc, 0xb4, 0xc5, 0x37, 0x35,
	0x81, 0x7c, 0xc1, 0x00, 0x19, 0xfe, 0x57, 0x79, 0x0a, 0x87, 0x9f, 0x71, 0xe4, 0x87, 0xd7, 0x89,
	0x13, 0xa6, 0xce, 0x1d, 0xf3, 0xa3, 0x70, 0x2e, 0x7f, 0x06, 0xc0, 0xb8, 0xfd, 0xb6, 0x60, 0xda,
	0x14, 0x95, 0xaf, 0xdc, 0xf9, 0x0a, 0x1e, 0x2f, 0x3b, 0xe3, 0x20, 0x23, 0xfb, 0xb0, 0xc1, 0xee,
	0x6f, 0x7d, 0x4f, 0x58, 0x54, 0xbb, 0xc5, 0xee, 0x07, 0x1e, 0xed, 0x81, 0x7e, 0x1e, 0x4d, 0x26,
	0x3e, 0x2b, 0xd9, 0xa8, 0xd4, 0xf0, 0x06, 0x0c, 0x3b, 0x0a, 0x02, 0xd7, 0xb9, 0x1b, 0xaf, 0x6a,
	0x19, 0x00, 0x9c, 0x79, 0x5e, 0x9d, 0x84, 0x74, 0x40, 0x1d, 0x63, 0xa6, 0x37, 0xc5, 0x61, 0xf8,
	0x27, 0x79, 0x04, 0x1b, 0x33, 0x27, 0x98, 0xa2, 0xae, 0x76, 0x15, 0x73, 0xcb, 0x96, 0x3f, 0xf4,
	0x3d, 0x6c, 0xcb, 0x0b, 0x5c, 0x2f, 0x8d, 0x0e, 0x61, 0xfb, 0x7b, 0xec, 0x39, 0xeb, 0xfa, 0x2a,
	0xba, 0x38, 0x01, 0xe8, 0x23, 0x5b, 0xb3, 0x85, 0x17, 0xa0, 0x09, 0x53, 0x1a, 0x47, 0x61, 0x8a,
	0x79, 0xb2, 0x52, 0x4c, 0xa6, 0xa0, 0x0d, 0xfd, 0xb4, 0x36, 0x9a, 0xfe, 0x82, 0x2d, 0xa9, 0x79,
	0x48, 0x7a, 0x0b, 0x6d, 0x61, 0x4e, 0x75, 0xa5, 0xab, 0x9a, 0xda, 0xf1, 0x53, 0x2b, 0x76, 0xad,
	0xa2, 0xc2, 0xba, 0x11, 0xcb, 0x17, 0x21, 0x4b, 0x32, 0xfb, 0x41, 0x6b, 0x7c, 0x00, 0xad, 0x50,
	0x9e, 0xf7, 0xab, 0x94, 0x1c, 0xbd, 0x59, 0x68, 0xf0, 0x63, 0xf3, 0x54, 0x39, 0xfe, 0xdd, 0x02,
	0xf5, 0xf2, 0xe6, 0x1b, 0x19, 0x40, 0x67, 0x71, 0xf8, 0xc9, 0x11, 0xdf, 0xbc, 0x02, 0x09, 0xe3,
	0xc0, 0x92, 0x2c, 0x59, 0x73, 0x96, 0xac, 0x0b, 0xce, 0x12, 0x6d, 0x90, 0x4f, 0xa0, 0x15, 0xc0,
	0x20, 0x07, 0x3c, 0x65, 0x99, 0x94, 0x9a, 0x80, 0x21, 0x74, 0x16, 0xa7, 0x5e, 0xf6, 0x52, 0x41,
	0x91, 0xf1, 0xa4, 0x7c, 0x31, 0x0e, 0x78, 0xda, 0x25, 0xec, 0x2d, 0x51, 0x41, 0xc4, 0xbd, 0x56,
	0xc1, 0x52, 0xd3, 0xda, 0x15, 0xec, 0x97, 0x10, 0x43, 0x9e, 0xf3, 0xb8, 0x6a, 0x94, 0x6a, 0x02,
	0x4d, 0x50, 0xfb, 0xc8, 0xc8, 0x0e, 0x0f, 0xc8, 0xe7, 0xd0, 0xd8, 0xfd, 0xfb, 0x2f, 0x9f, 0x9d,
	0x36, 0xc8, 0x4b, 0x68, 0xf1, 0x41, 0x20, 0xbb, 0xf9, 0x48, 0x48, 0x6d, 0x67, 0x71, 0x46, 0x68,
	0x83, 0xf4, 0x40, 0x3d, 0xf3, 0x3c, 0x19, 0x9b, 0xf3, 0x5a, 0xd3, 0xc7, 0x3b, 0x68, 0xcb, 0x37,
	0x22, 0x7b, 0xf9, 0x7b, 0xad, 0x64, 0x93, 0x2c, 0x4a, 0xdb, 0x3f, 0x5c, 0x56, 0xdb, 0xdc, 0xb6,
	0xa8, 0x9c, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x14, 0x56, 0x11, 0xa4, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KVSClient is the client API for KVS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVSClient interface {
	CreateOrGetTable(ctx context.Context, in *CreateOrGetTableRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionReply, error)
	CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RollbackTransaction(ctx context.Context, in *RollbackTransactionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type kVSClient struct {
	cc *grpc.ClientConn
}

func NewKVSClient(cc *grpc.ClientConn) KVSClient {
	return &kVSClient{cc}
}

func (c *kVSClient) CreateOrGetTable(ctx context.Context, in *CreateOrGetTableRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.KVS/CreateOrGetTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.KVS/DeleteTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionReply, error) {
	out := new(BeginTransactionReply)
	err := c.cc.Invoke(ctx, "/pb.KVS/BeginTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.KVS/CommitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) RollbackTransaction(ctx context.Context, in *RollbackTransactionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.KVS/RollbackTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/pb.KVS/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/pb.KVS/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.KVS/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.KVS/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.KVS/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVSServer is the server API for KVS service.
type KVSServer interface {
	CreateOrGetTable(context.Context, *CreateOrGetTableRequest) (*empty.Empty, error)
	DeleteTable(context.Context, *DeleteTableRequest) (*empty.Empty, error)
	BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionReply, error)
	CommitTransaction(context.Context, *CommitTransactionRequest) (*empty.Empty, error)
	RollbackTransaction(context.Context, *RollbackTransactionRequest) (*empty.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Add(context.Context, *AddRequest) (*empty.Empty, error)
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
	Update(context.Context, *UpdateRequest) (*empty.Empty, error)
}

// UnimplementedKVSServer can be embedded to have forward compatible implementations.
type UnimplementedKVSServer struct {
}

func (*UnimplementedKVSServer) CreateOrGetTable(ctx context.Context, req *CreateOrGetTableRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrGetTable not implemented")
}
func (*UnimplementedKVSServer) DeleteTable(ctx context.Context, req *DeleteTableRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTable not implemented")
}
func (*UnimplementedKVSServer) BeginTransaction(ctx context.Context, req *BeginTransactionRequest) (*BeginTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginTransaction not implemented")
}
func (*UnimplementedKVSServer) CommitTransaction(ctx context.Context, req *CommitTransactionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (*UnimplementedKVSServer) RollbackTransaction(ctx context.Context, req *RollbackTransactionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackTransaction not implemented")
}
func (*UnimplementedKVSServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedKVSServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedKVSServer) Add(ctx context.Context, req *AddRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedKVSServer) Delete(ctx context.Context, req *DeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedKVSServer) Update(ctx context.Context, req *UpdateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterKVSServer(s *grpc.Server, srv KVSServer) {
	s.RegisterService(&_KVS_serviceDesc, srv)
}

func _KVS_CreateOrGetTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrGetTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).CreateOrGetTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/CreateOrGetTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).CreateOrGetTable(ctx, req.(*CreateOrGetTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_DeleteTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).DeleteTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/DeleteTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).DeleteTable(ctx, req.(*DeleteTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_BeginTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).BeginTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/BeginTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).BeginTransaction(ctx, req.(*BeginTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/CommitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).CommitTransaction(ctx, req.(*CommitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_RollbackTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).RollbackTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/RollbackTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).RollbackTransaction(ctx, req.(*RollbackTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVS/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KVS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KVS",
	HandlerType: (*KVSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrGetTable",
			Handler:    _KVS_CreateOrGetTable_Handler,
		},
		{
			MethodName: "DeleteTable",
			Handler:    _KVS_DeleteTable_Handler,
		},
		{
			MethodName: "BeginTransaction",
			Handler:    _KVS_BeginTransaction_Handler,
		},
		{
			MethodName: "CommitTransaction",
			Handler:    _KVS_CommitTransaction_Handler,
		},
		{
			MethodName: "RollbackTransaction",
			Handler:    _KVS_RollbackTransaction_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KVS_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _KVS_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _KVS_Add_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KVS_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _KVS_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvserver.proto",
}
